### ISSUE TITLE
Add support for Enviroment variables in paths

### ISSUE THREAD

**Issue by enarhi** [BHoM/File_Toolkit#131]
#### Description:
File Adapter currently does not support environment variables. This could be easily added using 
`string path = Environment.ExpandEnvironmentVariables(value);`

![image](https://user-images.githubusercontent.com/6752345/156240462-ccd2dcb2-be0e-4b8c-8903-5f6eb6da3e7e.png)

**Comment by alelom** [comment]
@enarhi for this kind of usages, please also consider if the File_Engine method [`RelativiseUserPath()`](https://github.com/BHoM/File_Toolkit/blob/main/File_Engine/Modify/RelativiseUserPath.cs) can help you.

**Comment by enarhi** [comment]
@alelom that's handy. I'm happy with RelativiseUserPath being utilized in lieu of the adapter itself handling EnvironmentVariables then. Will leave it up to you if you think it's worth leaving the issue open and addressing, but as far as I'm concerned this can be closed as the current solution is more than acceptable!
